"""
Generate all figures for the LaTeX summary document.

This script loads optimized parameters for a specific trained circuit and generates
all the plots needed for the paper:
1. energy_vs_cycles.pdf - Energy density vs. number of cooling cycles
2. energy_heatmap_train.pdf - Energy difference heatmap on training grid
3. energy_heatmap_test.pdf - Energy difference heatmap on test grid
4. parameters_vs_layer.pdf - Optimized parameters vs. layer number
5. chern_vs_p.pdf - Chern number vs. circuit depth p

Note: energy_vs_p_by_res.pdf is generated by plot_progressive_circuit_expansion_results.py
"""

import numpy as np
import matplotlib.pyplot as plt
import os
import sys

# Add parent directory to path to import from variational_circuit_KSL_numba
sys.path.insert(0, os.path.dirname(__file__))

from variational_circuit_KSL_numba import (
    load_optimized_parameters_for_res_p,
    simulate_grid_with_analysis,
    plot_energy_density_vs_cycles,
    get_chern_number_from_single_particle_dm,
    simulate_grid,
    DATA_DIR,
    n_cycles_train,
    n_cycles_test
)

# Figure output directory
FIGURES_DIR = os.path.join(os.path.dirname(__file__), '../figures')
os.makedirs(FIGURES_DIR, exist_ok=True)


def plot_energy_vs_cycles(res_val=3, p_val=5, max_cycles=20):
    """
    Generate energy_vs_cycles.pdf showing energy density vs. number of cooling cycles
    
    Args:
        res_val: resolution parameter
        p_val: number of layers
        max_cycles: maximum number of cycles to plot
    """
    print(f"\n{'='*60}")
    print("Generating energy_vs_cycles.pdf")
    print(f"{'='*60}")
    
    # Load parameters
    strength_durations = load_optimized_parameters_for_res_p(res_val, p_val)
    
    # Set global p (needed for create_variational_circuit)
    import variational_circuit_KSL_numba as vc_module
    vc_module.p = p_val
    
    # Create grids
    n_k_points_train = 6 * res_val
    n_k_points_test = 6 * 20  # 120
    
    kx_list_train = np.linspace(-np.pi, np.pi, n_k_points_train + 1)[:-1]
    ky_list_train = np.linspace(-np.pi, np.pi, n_k_points_train + 1)[:-1]
    kx_list_test = np.linspace(-np.pi, np.pi, n_k_points_test + 1)[:-1]
    ky_list_test = np.linspace(-np.pi, np.pi, n_k_points_test + 1)[:-1]
    
    # Run simulation for training grid
    print(f"  Running simulation on training grid ({n_k_points_train}x{n_k_points_train}) with {max_cycles} cycles...")
    E_diff_train_all_cycles, _ = simulate_grid(kx_list_train, ky_list_train, strength_durations, max_cycles, verbose=False)
    
    # Run simulation for test grid
    print(f"  Running simulation on test grid ({n_k_points_test}x{n_k_points_test}) with {max_cycles} cycles...")
    E_diff_test_all_cycles, _ = simulate_grid(kx_list_test, ky_list_test, strength_durations, max_cycles, verbose=False)
    
    # Calculate energy densities for each cycle count
    cycle_counts = range(1, max_cycles + 1)
    energy_densities_train = []
    energy_densities_test = []
    
    for n_cycles in cycle_counts:
        # Training grid
        E_diff_train = E_diff_train_all_cycles[n_cycles - 1, :, :]
        energy_density_train = np.nanmean(E_diff_train) / 2
        energy_densities_train.append(energy_density_train)
        
        # Test grid
        E_diff_test = E_diff_test_all_cycles[n_cycles - 1, :, :]
        energy_density_test = np.nanmean(E_diff_test) / 2
        energy_densities_test.append(energy_density_test)
    
    # Create the plot
    plt.figure(figsize=(8, 6))
    plt.plot(cycle_counts, energy_densities_train, 'b-o', linewidth=2, markersize=6, 
             label=f'Train')
    plt.plot(cycle_counts, energy_densities_test, 'r-s', linewidth=2, markersize=6, 
             label=f'Test')
    
    # set x ticks according to the data and add labels only for every 5th tick
    plt.xticks(np.arange(0, max_cycles+1, 5)[1:])
    plt.ylim(0, max(energy_densities_train + energy_densities_test)*1.05)
    plt.xlabel('Cycle number', fontsize=20)
    plt.ylabel('Energy Density', fontsize=20)
    plt.grid(True, alpha=0.3)
    plt.legend(fontsize=17)
    plt.tick_params(labelsize=17)
    plt.tight_layout()
    
    # Save figure
    fig_path = os.path.join(FIGURES_DIR, 'energy_vs_cycles.pdf')
    plt.savefig(fig_path, dpi=300, bbox_inches='tight')
    print(f"  Saved to {fig_path}")
    plt.close()


def plot_energy_heatmap(res_val=3, p_val=5, grid_type='train'):
    """
    Generate energy heatmap - Energy difference heatmap on training or test grid
    
    Args:
        res_val: resolution parameter
        p_val: number of layers
        grid_type: 'train' or 'test' - determines which grid to use
    """
    grid_name = 'train' if grid_type == 'train' else 'test'
    print(f"\n{'='*60}")
    print(f"Generating energy_heatmap_{grid_name}.pdf")
    print(f"{'='*60}")
    
    # Load parameters
    strength_durations = load_optimized_parameters_for_res_p(res_val, p_val)
    
    # Set global p
    import variational_circuit_KSL_numba as vc_module
    vc_module.p = p_val
    
    # Determine grid size and cycles based on grid type
    if grid_type == 'train':
        n_k_points = 6 * res_val
        n_cycles = n_cycles_train
        show_training_points = False
    else:  # test
        n_k_points = 6 * 20  # 120
        n_cycles = n_cycles_test
        show_training_points = True
        n_k_points_train = 6 * res_val
    
    # Create grid
    kx_list = np.linspace(-np.pi, np.pi, n_k_points + 1)[:-1]
    ky_list = np.linspace(-np.pi, np.pi, n_k_points + 1)[:-1]
    
    # Run simulation
    print(f"  Running simulation on {grid_name} grid ({n_k_points}x{n_k_points})...")
    E_diff, _, _, _, _, _ = simulate_grid_with_analysis(
        kx_list, ky_list, strength_durations, n_cycles=n_cycles
    )
    
    # Extract final cycle if multiple cycles
    if E_diff.ndim == 3:
        E_diff_plot = E_diff[-1, :, :]
    else:
        E_diff_plot = E_diff
    
    # Create plot
    plt.figure(figsize=(8, 7))
    
    kx_coords = np.linspace(-np.pi, np.pi, n_k_points + 1)[:-1]
    ky_coords = np.linspace(-np.pi, np.pi, n_k_points + 1)[:-1]
    
    vmin = 0.0
    vmax = np.max(E_diff_plot)
    im = plt.pcolormesh(kx_coords, ky_coords, E_diff_plot, vmin=vmin, vmax=vmax, shading='auto')
    cbar = plt.colorbar(im, shrink=0.8)
    cbar.set_label('Energy difference', fontsize=20)
    cbar.ax.tick_params(labelsize=17)
    
    # Mark training points if this is test grid
    if show_training_points:
        step = (n_k_points - 1) / (n_k_points_train - 1)
        training_indices = np.round(np.arange(0, n_k_points, step)).astype(int)
        training_indices = training_indices[:n_k_points_train]
        
        kx_train_coords = kx_coords[training_indices]
        ky_train_coords = ky_coords[training_indices]
        
        for i, kx_coord in enumerate(kx_train_coords):
            for j, ky_coord in enumerate(ky_train_coords):
                plt.scatter(kx_coord, ky_coord, c='red', marker='x', s=50, linewidths=2, 
                           label='Training points' if i==0 and j==0 else "")
    
    plt.xlabel('$k_x$', fontsize=20)
    plt.ylabel('$k_y$', fontsize=20)
    if show_training_points:
        plt.legend(fontsize=17)
    plt.tick_params(labelsize=17)
    plt.axis('square')
    plt.tight_layout()
    
    # Save figure
    fig_path = os.path.join(FIGURES_DIR, f'energy_heatmap_{grid_name}.pdf')
    plt.savefig(fig_path, dpi=300, bbox_inches='tight')
    print(f"  Saved to {fig_path}")
    plt.close()


def plot_energy_heatmap_train(res_val=3, p_val=5):
    """Wrapper for backward compatibility"""
    plot_energy_heatmap(res_val, p_val, grid_type='train')


def plot_energy_heatmap_test(res_val=3, p_val=5):
    """Wrapper for backward compatibility"""
    plot_energy_heatmap(res_val, p_val, grid_type='test')


def plot_parameters_vs_layer(res_val=3, p_val=5):
    """
    Generate parameters_vs_layer.pdf - Optimized parameters vs. layer number
    
    Args:
        res_val: resolution parameter
        p_val: number of layers
    """
    print(f"\n{'='*60}")
    print("Generating parameters_vs_layer.pdf")
    print(f"{'='*60}")
    
    # Load parameters
    strength_durations = load_optimized_parameters_for_res_p(res_val, p_val)
    
    # Create plot
    plt.figure(figsize=(10, 6))
    
    terms = ['Jx', 'Jy', 'Jz', 'kappa', 'g', 'B']
    labels = ['$\\alpha_{x,\\ell}$ (Jx)', '$\\alpha_{y,\\ell}$ (Jy)', '$\\alpha_{z,\\ell}$ (Jz)', 
              '$\\delta_\\ell$ ($\\kappa$)', '$\\gamma_\\ell$ (g)', '$\\beta_\\ell$ (B)']
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b']
    linestyles = ['-', '-', '-', '-', '-', '-']
    
    for i, (term, label, color, ls) in enumerate(zip(terms, labels, colors, linestyles)):
        plt.plot(range(1, p_val + 1), strength_durations[term], 
                label=label, marker='o', linewidth=2, markersize=6, color=color, linestyle=ls)
    
    # set x ticks according to the data
    plt.xticks(np.arange(1, p_val + 1))
    plt.xlabel('Layer number $\\ell$', fontsize=24)
    plt.ylabel('Parameter value', fontsize=24)
    plt.legend(fontsize=20, ncol=2)
    plt.tick_params(labelsize=20)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    
    # Save figure
    fig_path = os.path.join(FIGURES_DIR, 'parameters_vs_layer.pdf')
    plt.savefig(fig_path, dpi=300, bbox_inches='tight')
    print(f"  Saved to {fig_path}")
    plt.close()


def main(res_val, p_val):
    """
    Generate all figures for the LaTeX document
    
    Args:
        res_val: resolution parameter (default: 3)
        p_val: number of layers for most plots (default: 5)
        p_values_for_chern: list of p values for Chern number plot (default: [3,4,5,6,7,8,9,10])
    """
    print("="*60)
    print("GENERATING ALL FIGURES FOR LATEX SUMMARY")
    print("="*60)
    print(f"Using res={res_val}, p={p_val} for main plots")
    print(f"Figures will be saved to: {FIGURES_DIR}")
    print("="*60)
    
    # Generate all figures
    plot_energy_vs_cycles(res_val, p_val, max_cycles=20)
    plot_energy_heatmap_train(res_val, p_val)
    plot_energy_heatmap_test(res_val, p_val)
    plot_parameters_vs_layer(res_val, p_val)
    
    print("\n" + "="*60)
    print("ALL FIGURES GENERATED SUCCESSFULLY")
    print("="*60)
    print(f"Figures saved to: {FIGURES_DIR}")
    print("\nNote: energy_vs_p_by_res.pdf and chern_vs_p.pdf should be generated separately")
    print("      using plot_progressive_circuit_expansion_results.py")
    print("="*60)


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description='Generate all figures for LaTeX summary')
    parser.add_argument('--res', type=int, default=3, help='Resolution parameter (default: 3)')
    parser.add_argument('--p', type=int, default=5, help='Number of layers for main plots (default: 5)')
    
    args = parser.parse_args()
    
    main(res_val=args.res, p_val=args.p)

