"""
Generate all figures for the LaTeX summary document.

This script loads optimized parameters for a specific trained circuit and generates
all the plots needed for the paper:
1. energy_vs_cycles.pdf - Energy density vs. number of cooling cycles
2. energy_heatmap_train.pdf - Energy difference heatmap on training grid
3. energy_heatmap_test.pdf - Energy difference heatmap on test grid
4. parameters_vs_layer.pdf - Optimized parameters vs. layer number
5. chern_vs_p.pdf - Chern number vs. circuit depth p

Note: energy_vs_p_by_res.pdf is generated by plot_progressive_circuit_expansion_results.py
"""

import numpy as np
import matplotlib.pyplot as plt
import os
import sys

# Add parent directory to path to import from variational_circuit_KSL_numba
sys.path.insert(0, os.path.dirname(__file__))

from variational_circuit_KSL_numba import (
    load_optimized_parameters_for_res_p,
    simulate_grid_with_analysis,
    plot_energy_density_vs_cycles,
    get_chern_number_from_single_particle_dm,
    simulate_grid,
    DATA_DIR,
    n_cycles_train,
    n_cycles_test
)

# Figure output directory
FIGURES_DIR = os.path.join(os.path.dirname(__file__), '../figures')
os.makedirs(FIGURES_DIR, exist_ok=True)


def plot_energy_vs_cycles(res_val=3, p_val=5, max_cycles=20):
    """
    Generate energy_vs_cycles.pdf showing energy density vs. number of cooling cycles
    
    Args:
        res_val: resolution parameter
        p_val: number of layers
        max_cycles: maximum number of cycles to plot
    """
    print(f"\n{'='*60}")
    print("Generating energy_vs_cycles.pdf")
    print(f"{'='*60}")
    
    # Load parameters
    strength_durations = load_optimized_parameters_for_res_p(res_val, p_val)
    
    # Set global p (needed for create_variational_circuit)
    import variational_circuit_KSL_numba as vc_module
    vc_module.p = p_val
    
    # Create grids
    n_k_points_train = 1 + 6 * res_val
    n_k_points_test = 1 + 6 * 20  # 121
    
    kx_list_train = np.linspace(-np.pi, np.pi, n_k_points_train)
    ky_list_train = np.linspace(-np.pi, np.pi, n_k_points_train)
    kx_list_test = np.linspace(-np.pi, np.pi, n_k_points_test)
    ky_list_test = np.linspace(-np.pi, np.pi, n_k_points_test)
    
    # Run simulation for training grid
    print(f"  Running simulation on training grid ({n_k_points_train}x{n_k_points_train}) with {max_cycles} cycles...")
    E_diff_train_all_cycles, _ = simulate_grid(kx_list_train, ky_list_train, strength_durations, max_cycles, verbose=False)
    
    # Run simulation for test grid
    print(f"  Running simulation on test grid ({n_k_points_test}x{n_k_points_test}) with {max_cycles} cycles...")
    E_diff_test_all_cycles, _ = simulate_grid(kx_list_test, ky_list_test, strength_durations, max_cycles, verbose=False)
    
    # Calculate energy densities for each cycle count
    cycle_counts = range(1, max_cycles + 1)
    energy_densities_train = []
    energy_densities_test = []
    
    for n_cycles in cycle_counts:
        # Training grid
        E_diff_train = E_diff_train_all_cycles[n_cycles - 1, :, :]
        energy_density_train = np.nanmean(E_diff_train) / 2
        energy_densities_train.append(energy_density_train)
        
        # Test grid
        E_diff_test = E_diff_test_all_cycles[n_cycles - 1, :, :]
        energy_density_test = np.nanmean(E_diff_test) / 2
        energy_densities_test.append(energy_density_test)
    
    # Create the plot
    plt.figure(figsize=(8, 6))
    plt.plot(cycle_counts, energy_densities_train, 'b-o', linewidth=2, markersize=6, 
             label=f'Training Grid ({n_k_points_train}x{n_k_points_train})')
    plt.plot(cycle_counts, energy_densities_test, 'r-s', linewidth=2, markersize=6, 
             label=f'Test Grid ({n_k_points_test}x{n_k_points_test})')
    
    plt.xlabel('Number of Cooling Cycles', fontsize=12)
    plt.ylabel('Energy Density', fontsize=12)
    plt.title(f'Energy Density vs. Number of Cooling Cycles\n(res={res_val}, p={p_val})', fontsize=12)
    plt.grid(True, alpha=0.3)
    plt.legend(fontsize=10)
    plt.tight_layout()
    
    # Save figure
    fig_path = os.path.join(FIGURES_DIR, 'energy_vs_cycles.pdf')
    plt.savefig(fig_path, dpi=300, bbox_inches='tight')
    print(f"  Saved to {fig_path}")
    plt.close()


def plot_energy_heatmap_train(res_val=3, p_val=5):
    """
    Generate energy_heatmap_train.pdf - Energy difference heatmap on training grid
    
    Args:
        res_val: resolution parameter
        p_val: number of layers
    """
    print(f"\n{'='*60}")
    print("Generating energy_heatmap_train.pdf")
    print(f"{'='*60}")
    
    # Load parameters
    strength_durations = load_optimized_parameters_for_res_p(res_val, p_val)
    
    # Set global p
    import variational_circuit_KSL_numba as vc_module
    vc_module.p = p_val
    
    # Create training grid
    n_k_points_train = 1 + 6 * res_val
    kx_list_train = np.linspace(-np.pi, np.pi, n_k_points_train)
    ky_list_train = np.linspace(-np.pi, np.pi, n_k_points_train)
    
    # Run simulation
    print(f"  Running simulation on training grid ({n_k_points_train}x{n_k_points_train})...")
    E_diff, _, _, _, _, _ = simulate_grid_with_analysis(
        kx_list_train, ky_list_train, strength_durations, n_cycles=n_cycles_train
    )
    
    # Extract final cycle if multiple cycles
    if E_diff.ndim == 3:
        E_diff_plot = E_diff[-1, :, :]
    else:
        E_diff_plot = E_diff
    
    # Create plot
    plt.figure(figsize=(8, 7))
    
    kx_coords = np.linspace(-np.pi, np.pi, n_k_points_train)
    ky_coords = np.linspace(-np.pi, np.pi, n_k_points_train)
    
    vmin = 0.0
    vmax = np.max(E_diff_plot)
    im = plt.pcolormesh(kx_coords, ky_coords, E_diff_plot, vmin=vmin, vmax=vmax, shading='auto')
    plt.colorbar(im, label='Energy difference', shrink=0.8)
    
    plt.xlabel('$k_x$', fontsize=12)
    plt.ylabel('$k_y$', fontsize=12)
    plt.title(f'Energy Difference Heatmap - Training Grid\n(res={res_val}, p={p_val}, {n_k_points_train}$\\times${n_k_points_train} points)', fontsize=12)
    plt.tight_layout()
    
    # Save figure
    fig_path = os.path.join(FIGURES_DIR, 'energy_heatmap_train.pdf')
    plt.savefig(fig_path, dpi=300, bbox_inches='tight')
    print(f"  Saved to {fig_path}")
    plt.close()


def plot_energy_heatmap_test(res_val=3, p_val=5):
    """
    Generate energy_heatmap_test.pdf - Energy difference heatmap on test grid with training points marked
    
    Args:
        res_val: resolution parameter
        p_val: number of layers
    """
    print(f"\n{'='*60}")
    print("Generating energy_heatmap_test.pdf")
    print(f"{'='*60}")
    
    # Load parameters
    strength_durations = load_optimized_parameters_for_res_p(res_val, p_val)
    
    # Set global p
    import variational_circuit_KSL_numba as vc_module
    vc_module.p = p_val
    
    # Create grids
    n_k_points_train = 1 + 6 * res_val
    n_k_points_test = 1 + 6 * 20  # 121
    
    kx_list_test = np.linspace(-np.pi, np.pi, n_k_points_test)
    ky_list_test = np.linspace(-np.pi, np.pi, n_k_points_test)
    
    # Run simulation
    print(f"  Running simulation on test grid ({n_k_points_test}x{n_k_points_test})...")
    E_diff, _, _, _, _, _ = simulate_grid_with_analysis(
        kx_list_test, ky_list_test, strength_durations, n_cycles=n_cycles_test
    )
    
    # Extract final cycle if multiple cycles
    if E_diff.ndim == 3:
        E_diff_plot = E_diff[-1, :, :]
    else:
        E_diff_plot = E_diff
    
    # Create plot
    plt.figure(figsize=(8, 7))
    
    kx_coords = np.linspace(-np.pi, np.pi, n_k_points_test)
    ky_coords = np.linspace(-np.pi, np.pi, n_k_points_test)
    
    vmin = 0.0
    vmax = np.max(E_diff_plot)
    im = plt.pcolormesh(kx_coords, ky_coords, E_diff_plot, vmin=vmin, vmax=vmax, shading='auto')
    plt.colorbar(im, label='Energy difference', shrink=0.8)
    
    # Mark training points
    step = (n_k_points_test - 1) / (n_k_points_train - 1)
    training_indices = np.round(np.arange(0, n_k_points_test, step)).astype(int)
    training_indices = training_indices[:n_k_points_train]
    
    kx_train_coords = kx_coords[training_indices]
    ky_train_coords = ky_coords[training_indices]
    
    for i, kx_coord in enumerate(kx_train_coords):
        for j, ky_coord in enumerate(ky_train_coords):
            plt.scatter(kx_coord, ky_coord, c='red', marker='x', s=50, linewidths=2, 
                       label='Training points' if i==0 and j==0 else "")
    
    plt.xlabel('$k_x$', fontsize=12)
    plt.ylabel('$k_y$', fontsize=12)
    plt.title(f'Energy Difference Heatmap - Test Grid\n(res={res_val}, p={p_val}, {n_k_points_test}$\\times${n_k_points_test} points)', fontsize=12)
    plt.legend(fontsize=10)
    plt.tight_layout()
    
    # Save figure
    fig_path = os.path.join(FIGURES_DIR, 'energy_heatmap_test.pdf')
    plt.savefig(fig_path, dpi=300, bbox_inches='tight')
    print(f"  Saved to {fig_path}")
    plt.close()


def plot_parameters_vs_layer(res_val=3, p_val=5):
    """
    Generate parameters_vs_layer.pdf - Optimized parameters vs. layer number
    
    Args:
        res_val: resolution parameter
        p_val: number of layers
    """
    print(f"\n{'='*60}")
    print("Generating parameters_vs_layer.pdf")
    print(f"{'='*60}")
    
    # Load parameters
    strength_durations = load_optimized_parameters_for_res_p(res_val, p_val)
    
    # Create plot
    plt.figure(figsize=(10, 6))
    
    terms = ['Jx', 'Jy', 'Jz', 'kappa', 'g', 'B']
    labels = ['$\\alpha_x$ (Jx)', '$\\alpha_y$ (Jy)', '$\\alpha_z$ (Jz)', 
              '$\\beta$ ($\\kappa$)', '$\\gamma$ (g)', '$\\delta$ (B)']
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b']
    linestyles = ['-', '-', '-', '-', '-', '-']
    
    for i, (term, label, color, ls) in enumerate(zip(terms, labels, colors, linestyles)):
        plt.plot(range(1, p_val + 1), strength_durations[term], 
                label=label, marker='o', linewidth=2, markersize=6, color=color, linestyle=ls)
    
    plt.xlabel('Layer $\\ell$', fontsize=12)
    plt.ylabel('Strength $\\times$ Duration', fontsize=12)
    plt.title(f'Optimized Variational Parameters vs. Layer Number\n(res={res_val}, p={p_val})', fontsize=12)
    plt.legend(fontsize=10, ncol=2)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    
    # Save figure
    fig_path = os.path.join(FIGURES_DIR, 'parameters_vs_layer.pdf')
    plt.savefig(fig_path, dpi=300, bbox_inches='tight')
    print(f"  Saved to {fig_path}")
    plt.close()


def main(res_val=3, p_val=5):
    """
    Generate all figures for the LaTeX document
    
    Args:
        res_val: resolution parameter (default: 3)
        p_val: number of layers for most plots (default: 5)
        p_values_for_chern: list of p values for Chern number plot (default: [3,4,5,6,7,8,9,10])
    """
    print("="*60)
    print("GENERATING ALL FIGURES FOR LATEX SUMMARY")
    print("="*60)
    print(f"Using res={res_val}, p={p_val} for main plots")
    print(f"Figures will be saved to: {FIGURES_DIR}")
    print("="*60)
    
    # Generate all figures
    plot_energy_vs_cycles(res_val, p_val, max_cycles=20)
    plot_energy_heatmap_train(res_val, p_val)
    plot_energy_heatmap_test(res_val, p_val)
    plot_parameters_vs_layer(res_val, p_val)
    
    print("\n" + "="*60)
    print("ALL FIGURES GENERATED SUCCESSFULLY")
    print("="*60)
    print(f"Figures saved to: {FIGURES_DIR}")
    print("\nNote: energy_vs_p_by_res.pdf and chern_vs_p.pdf should be generated separately")
    print("      using plot_progressive_circuit_expansion_results.py")
    print("="*60)


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description='Generate all figures for LaTeX summary')
    parser.add_argument('--res', type=int, default=3, help='Resolution parameter (default: 3)')
    parser.add_argument('--p', type=int, default=5, help='Number of layers for main plots (default: 5)')
    
    args = parser.parse_args()
    
    main(res_val=args.res, p_val=args.p)

